### PR TITLE
Enhance GHA `check-complexity-eligibility.js` to use `label-directory.json`

### LINKED ISSUE #7535: Enhance GHA `check-complexity-eligibility.js` to use `label-directory.json`
### Overview
We want to refactor the GHA workflows to reference each label by a general ID (i.e. a 'labelKey') rather than the label's name so that other HfLA project groups can use these workflows without needing to match the label names used by the Website team.

### Details
Currently, the GHA workflows files that add, remove, and change labels on issues identify each label by its name (i.e. the 'labelName') directly. Instead of hard-coding each label name, we want these files to identify each label by its 'labelKey' and use the `retrieve-label-directory.js` module to look up the corresponding 'labelName' that is needed in order for the REST API to apply labels to issues.

### Action Items
This issue involves specifically the `check-complexity-eligibility.js` function of the "**_Issue Trigger_**" GitHub Action, and you must set up your environment for testing GHAs in order to work on this issue. See notes below in "Resources/ Instructions", and ask questions if you need additional help- GHAs can be tricky, and if you get stuck somewhere, someone who has worked on these before might have information that will save you a lot of time.    
- [x] Before making any of the edits following, first create a test branch in your repo and demonstrate the current, correct behavior of the "Issue Trigger" GHA. Afterwards, create an additional branch for the edits following- this is the branch that will be attached to the PR.

Refer to [check-complexity-eligibility.js](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-issue/add-preliminary-comment/check-complexity-eligibility.js).
- [x]  A preliminary search found that this file uses the following labels. As you work through this issue, confirm that this list is correct, and note any additions or subtractions as needed:
  - `ER`
  - `epic`
  - `role: front end`
  - `role: back end/devOps`
  - `Complexity:  Prework`,
  - `good first issue`
  - `Complexity: Small`
  - `Complexity: Medium` 
  
- [x] Insert on the very first line the comment: `// Import modules` 
- [x] Then insert this module after `const fs = require('fs');`  
  ```
  const retrieveLabelDirectory = require('../../utils/retrieve-label-directory');
  ```
- [x] Add a space after the `Import modules` block, then insert the comment:
  ```
  // Use labelKeys to retrieve current labelNames from directory
  ```
  then for each label, consult [label-directory.json](https://github.com/hackforla/website/blob/gh-pages/github-actions/utils/_data/label-directory.json) and replace labelName with the labelKey:
  ```
  const [
    er,
    epic,
    roleFrontEnd,
    roleBackEndDevOps,
    complexity0,
    complexity1,
    complexity2,
    complexity3,
    statusUnassignedByBot,
  ] = [
    “er”,
    “epic”, 
    “roleFrontEnd”,
    “roleBackEndDevOps”,
    "complexity0",
    "complexity1",
    "complexity2",
    "complexity3",
    "statusUnassignedByBot",
  ].map(retrieveLabelDirectory);
  ```
- [x] Consolidate `requiredRoleLabels`, `requiredComplexityLabels`, `exceptionLabels` with label assignments
- [x] Search the code for instances of the original label name and substitute the <labelKey> defined above.
- [x] Prior to submitting the PR, search for all code comment that reference a specific label name
  - [x] List these instances out in a comment on this issue, with your suggestion for replacement text that generalizes it.
  - [ ] When finished, add the label `ready for product` and change status to "Questions / In Review" 
  - [ ] Product will review and provide feedback on replacement text for revision or sign-off on changes.
- [x] Perform a test in your own repo that demonstrates that there is no change to the GHA's functionality after making the edits.

### Resources/Instructions
- Refer to [Hack for LA's GitHub Actions (current revision)](https://github.com/hackforla/website/issues/6537#issuecomment-2041147335), especially Tips 6, 7, and 8, if you have not already created you personal environment for testing.
- [How to Test GitHub Actions](https://drive.google.com/drive/u/0/folders/1MPY9CKcfKKN7hpDCG46ARrRzRSM8d8OA)
- [Additional Notes for GitHub Actions](https://docs.google.com/document/d/1frtvr5twBa_3yRGCG0divhlOMW8dPJxT/edit)
- This issue is part of the epic #6454

### PR DESCRIPTION
**Pull request by t-will-gillis**
Fixes #7535 

### What changes did you make?
  
  - Using labelKeys to retrieve current labelNames from directory
  - Consolidated the `EXCEPTION_LABELS`, `REQUIRED_ROLE_LABELS`, `REQUIRED_COMPLEXITY_LABELS` with new label assignments
  - Changed status field designations to HARD_CODED 
  - Fixed an existing error where the specified status was incorrect 'In Progress' --> 'In progress (actively working' actual

### Why did you make the changes (we will use this info to test)?
  
  - Refactoring the label assignments so that other HfLA groups can use workflows also
  - Also, this allows us to change the label name without worrying about code crashing 

<h3>CodeQL Alerts</h3>

After the PR has been submitted and the resulting GitHub actions/checks have been completed, developers should check the PR for CodeQL alert annotations.

<details><summary>Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown</summary>
  
Screenshot 2024-10-28 154514

</details>

Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [x] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and (select one):
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>

If CodeQL alert/annotations appear, refer to [How to Resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270).  

In general, CodeQL alerts should be resolved prior to PR reviews and merging

</details>

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

- No visual changes
- [Workflow log showing successful substitutions](https://github.com/t-will-gillis/website/actions/runs/14228083605)
- [Issue showing automation working still](https://github.com/t-will-gillis/website/issues/1153)

## Notes for Reviewers- Testing
If you want to do your own testing for this issue, you probably want to limit the scope of your tests because this automation covers many different scenarios. To proceeed, you will need to set up your environment first:
- Refer to [Hack for LA's GitHub Actions (current revision)](https://github.com/hackforla/website/issues/6537#issuecomment-2041147335), especially Tips 6, 7, and 8, if you have not already created your personal environment for testing.
- Follow the instructions for installing HfLA labels to your repo by following jphamtv 's instructions on the command line, _**OR**_ in your own repo, enter the relevant labels manually. 
- [1 How to Test GitHub Actions](https://drive.google.com/drive/u/0/folders/1MPY9CKcfKKN7hpDCG46ARrRzRSM8d8OA)
- [2 Additional Notes for GitHub Actions](https://docs.google.com/document/d/1frtvr5twBa_3yRGCG0divhlOMW8dPJxT/edit)
- Go to [preliminary-update-comment.js](github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js) and find the line for `const isAdminOrMerge = await...` and replace with:  
  ```  
    // const isAdminOrMerge = await memberOfAdminOrMergeTeam();
    const isAdminOrMerge = false;
  ```  
-  Go to [get-timeline.js](github-actions/utils/get-timeline.js), find line `owner: context.repo.owner,` and replace with whatever your GitHub handle is. For me it looks like this: `owner: 't-will-gillis',` Notice that your handle needs to be in quotes, and include the comma at the end.
- Your test will not change issue statuses, and the workflow will fail in this step. But you should be able to see that the main steps are being completed.
- If you would like more info, or if you are getting an error that makes no sense, please contact me.

### CODE REVIEW

**Comment by gmgonzal** [comment]
Review ETA: 4/8

File: github-actions/trigger-issue/add-preliminary-comment/check-complexity-eligibility.js [hunk 1]
```diff
@@ -353,18 +373,18 @@ async function handleIssueComplexityNotPermitted(
       owner,
```
Comment (gmgonzal) [inline github-actions/trigger-issue/add-preliminary-comment/check-complexity-eligibility.js:373]: - [ ] use new var for 'Status: Unassigned by Bot' on line 372

File: github-actions/trigger-issue/add-preliminary-comment/check-complexity-eligibility.js [hunk 2]
```diff
@@ -353,18 +373,18 @@ async function handleIssueComplexityNotPermitted(
...
       github,
       context,
       projectItemId,
-      statusFieldIds('New_Issue_Approval')
+      statusFieldIds(NEW_ISSUE_APPROVAL)
     );
   
-    // If the assignee's Pre-work Checklist (Skills Issue) is closed, open it
+    // If the assignee's Skills Issue (Pre-work Checklist) is closed, open it
     if (preWorkIssue.state === 'closed') {
```
Comment (gmgonzal) [inline github-actions/trigger-issue/add-preliminary-comment/check-complexity-eligibility.js:388]: - [ ] consider adding a new const for hard coded value 'closed'

File: github-actions/trigger-issue/add-preliminary-comment/check-complexity-eligibility.js [hunk 3]
```diff
@@ -373,16 +393,16 @@ async function handleIssueComplexityNotPermitted(
         state: 'open',
```
Comment (gmgonzal) [inline github-actions/trigger-issue/add-preliminary-comment/check-complexity-eligibility.js:393]: - [ ] consider adding a new const for hard coded value 'open'

**Review by gmgonzal — COMMENTED** [review]
Hi @t-will-gillis , code changes look good! There are some minor edits I suggest we should make, let me know what you think. 

I will try to validate the changes on my end. Will update by tomorrow latest (4/10).

Thanks!

**Review by gmgonzal — APPROVED** [review]
@t-will-gillis after some hacking, I was able to validate the action on my end. Approved!

[Test issue](https://github.com/gmgonzal/website/issues/6)
[Passing Action](https://github.com/gmgonzal/website/actions/runs/14370326215/job/40292050886)
