### PR TITLE
Remove blank roles from Wins filter options

### LINKED ISSUE #4592: Remove blank roles from WINS filter options
### Overview
As developers we need to prevent the display of blank role filter options (checkboxes) on the WINS page, so that the page does not appear as if something is broken or missing.   

### Details
The problem is depicted in the screenshot in the Resources section below.  The filter options are generated dynamically from the displayed WINS data.   The code should be modified so that even if a WINS submission with a blank role is displayed, it will not cause a blank role option checkbox to be displayed.   

### Action Items
- [x] Update the JavaScript in `assets/js/wins.js` so that blank role filter options (checkboxes) are not displayed. 

### Resources/Instructions
<details><summary>Screenshot depicting a blank role checkbox</summary>

image

</details> 

- [JavaScript for WINS page - GitHub](https://github.com/hackforla/website/blob/gh-pages/assets/js/wins.js)
- WINS page [GitHub](https://github.com/hackforla/website/blob/gh-pages/pages/wins/wins.html) | [webpage](https://hackforla.org/wins)

### PR DESCRIPTION
**Pull request by pdimaano**
Fixes #4592

### What changes did you make and why did you make them ?

  - Added conditional statement to remove blank checkbox option from dropdown menu
  - Fixed spelling error with name of dropdown variable
  - Removed unnecessary spaces for formatting

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2023-05-19 at 11 42 18 AM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screen Shot 2023-05-19 at 11 44 24 AM

</details>

### CODE REVIEW

**Comment by Sebster3** [comment]
Availability: 5/19-5/20
ETA: 5/19

**Review by Sebster3 — COMMENTED** [review]
Hey @pdimaano, great job working on this PR!

The basics all look good: The branches are correct, the site renders successfully in my local environment, and the changes you've made correctly prevent blank roles from appearing in the filter dropdown.

I've left some thoughts below that I'd like to get your opinion on. let me know what you think, cheers!

File: assets/js/wins.js [hunk 1]
```diff
@@ -110,9 +110,13 @@
...
   		cloneFilterTemplate.querySelector("input").addEventListener("click",checkboxClickHandler);
-			cloneFilterTemplate.querySelector("label").textContent = `${key}`;
-  		cloneFilterTemplate.querySelector("label").htmlFor =`role_${key.replace(/\s+/g, '')}`;
-  		roleDropwDown.append(cloneFilterTemplate);
+			if (key !== '') {
+				cloneFilterTemplate.querySelector("label").textContent = `${key}`;
+				cloneFilterTemplate.querySelector("label").htmlFor =`role_${key.replace(/\s+/g, '')}`;
+			} else {
+				continue
+			}
```
Comment (Sebster3) [inline assets/js/wins.js]: The parent loop appears to be building a filter entry bit by bit, then appending the new entry to the filter dropdown at the end of the loop.

The current placement of the conditional statement implies that the preceding lines in the loop should run regardless of `key`s state, however the work done in the preceding lines is discarded if `key` is empty.

As a suggestion, the conditional statement could be moved to the top of the for loop and simplified to:

```js
if ( /* key is an empty string*/ ) {
    continue
}
```

Doing so would make it clear that the body of the loop should **not** run if `key` is empty and makes the code easier to read (less nesting).

Comment (pdimaano) [reply assets/js/wins.js]: @Sebster3 Thank you for the recommendation. I changed the location of the conditional statement for clarity and it looks like the dropdown menu is still being generated correctly.

Comment (Sebster3) [reply assets/js/wins.js]: Thanks for considering it @pdimaano, and I'm glad it seemed like a worthwhile change!

One last suggestion, the `else` block surrounding the lines handling `cloneFilterTemplate` could be dropped since those lines would only run when `key` is not an empty string, thus making the `else` redundant.

```js
for(const [key,value] of Object.entries(roleHash) ){
	if (key === '') {
		continue
	}
	
	let cloneFilterTemplate = filterTemplate.content.firstElementChild.cloneNode(true);
	cloneFilterTemplate.querySelector("input").value = `role_${key}`;
	cloneFilterTemplate.querySelector("input").id = `role_${key.replace(/\s+/g, '')}`;
	cloneFilterTemplate.querySelector("input").name = `role_${key.replace(/\s+/g, '')}`;
	cloneFilterTemplate.querySelector("input").addEventListener("click",checkboxClickHandler);
	cloneFilterTemplate.querySelector("label").textContent = `${key}`;
	cloneFilterTemplate.querySelector("label").htmlFor =`role_${key.replace(/\s+/g, '')}`;
	roleDropDown.append(cloneFilterTemplate);
}
```

**Comment by mjshelton12** [comment]
Availability: Sunday 1pm-5pm, Mon-Fri 9am-1pm
ETA: 5/21 end of day

**Comment by roslynwythe** [comment]
Availability 5/21 9 - 11 pm 
ETA 5/22 EOD

**Review by Sebster3 — DISMISSED** [review]
Everything still looks good following the recent changes. The site builds & renders correctly and the action item in the issue was addressed. Approved!

**Review by mjshelton12 — DISMISSED** [review]
First off, great work on the basics. Your branches are correct, you linked to an issue, you provided a thorough explanation of what you did/why you did it, and included appropriate visuals. Your code is clean and effective, plus it shows perfectly in chrome desktop, tablet, and phone as well as safari desktop. Excellent work!

You did a great job finding the cleanest and most effective way to write this code block - I can see by your adjustments in pushes. I liked seeing how you came to the code you ultimately want merged, it helped me see your process. Very nice work and thank you for fixing that blank checkmark!

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Excellent work @pdimaano - your branches are setup correctly and your PR is well-formed and descriptive and it checks out fine in the browser.  My only request is to change the indenting of the code so that it is consistent with the other indenting on the page.  Inconsistent indenting can cause confusion, if for example the next developer to work on this has an automated prettifier which modifies the lines of code that you changed.

File: assets/js/wins.js [hunk 2]
```diff
@@ -100,20 +100,22 @@
...
-  		let cloneFilterTemplate = filterTemplate.content.firstElementChild.cloneNode(true);
-  		cloneFilterTemplate.querySelector("input").value = `role_${key}`;
-			cloneFilterTemplate.querySelector("input").id = `role_${key.replace(/\s+/g, '')}`;
-			cloneFilterTemplate.querySelector("input").name = `role_${key.replace(/\s+/g, '')}`;
-  		cloneFilterTemplate.querySelector("input").addEventListener("click",checkboxClickHandler);
-			cloneFilterTemplate.querySelector("label").textContent = `${key}`;
-  		cloneFilterTemplate.querySelector("label").htmlFor =`role_${key.replace(/\s+/g, '')}`;
-  		roleDropwDown.append(cloneFilterTemplate);
-
+			if (key === '') {
```
Comment (roslynwythe) [inline assets/js/wins.js]: Hi @pdimaano your code does work perfectly but for the sake of other developers we do want to indent code consistently.  Line 108 should be indented one tab to the right of line 107.  Lines 111-118 and lines 121-128 should be at that same indent level as line 108.  Thank you.

Comment (pdimaano) [reply assets/js/wins.js]: @roslynwythe I made the code formatting changes according to your prior comment and it looks fine in my code editor. However, when I view the code in GitHub there seem to be some slight differences with the appearance and indentation. I also ran the updated code on my local system which still works to fix the issue. Are these changes still alright?

Comment (roslynwythe) [reply assets/js/wins.js]: Hi @pdimaano are you using a linter or prettifier like pretty print that might be messing up the indenting?

**Comment by ronaldpaek** [comment]
@pdimaano I think I found the issue, my vscode also was causing issues with every file I was modifying inserting a /n

**Comment by ronaldpaek** [comment]
@pdimaano I actually never used eslint as a formatter, but the way hack4la has it set up the only workspace rules defined is with .stylelintrc.json which I think a linter and so if you apply that it will follow the rules, but I also have it not apply any prettier formatting if there is no configuration files

Screenshot 2023-06-20 at 8 39 32 PM
pdimaano

**Comment by ronaldpaek** [comment]
@pdimaano 
https://marketplace.visualstudio.com/items?itemName=tombonnike.vscode-status-bar-format-toggle
https://www.robinwieruch.de/how-to-use-prettier-vscode/

**Comment by pdimaano** [comment]
@roslynwythe I disabled the ESLint and Prettier extensions in my VS Code editor but apparently I cannot push another commit since no actual code in the JavaScript file was changed. I checked that the code still works in Docker. Is there a way around this and would it fix the issues with indentation and formatting?

**Comment by blulady** [comment]
> @roslynwythe I disabled the ESLint and Prettier extensions in my VS Code editor but apparently I cannot push another commit since no actual code in the JavaScript file was changed. I checked that the code still works in Docker. Is there a way around this and would it fix the issues with indentation and formatting?

So the easiest thing to do would be to create slight change commit it & push it & then change it back & push it. There is probably a better way.

**Comment by pdimaano** [comment]
@blulady @roslynwythe I disabled the ESLint and Prettier extensions and made the commits as suggested previously. I made sure to check that line 108 is one tab to the right of line 107 and lines 111-118 and 121-128 are at the same indent level as line 108. I ran the application in Docker to make sure the code still works as intended. Does this fix the issues with indentation and formatting?

**Comment by roslynwythe** [comment]
Hi @pdimaano please browse to the "Files Changed" page then click on the triple-dot menu icon, then "View File"
image

-------
then see lines 107-128:
image

---------
Is this what you see in your IDE?

**Comment by pdimaano** [comment]
@roslynwythe This is how the code appears in my VSCode editor (I made sure to check ESLint and Prettier extensions were disabled):
Screen Shot 2023-07-06 at 11 54 01 AM

**Comment by pdimaano** [comment]
@roslynwythe I made some commits after comparing the formatting differences with the code in VSCode, TextEdit and GitHub. It looks like the JavaScript file as it appears in GitHub now follows the formatting specifications that we discussed previously. I believe the appropriate lines are now indented and formatted correctly. I also ran it Docker as well to make sure it still works as intended. Please let me know if this is correct.

**Review by roslynwythe — APPROVED** [review]
Thank you @pdimaano for your hard work on this issue.  The code change is correct, clean and well-formatted, the PR is well-formed and descriptive, and the code checks out in the browser.  I appreciate the extra effort to get the clean indenting; that helps make the code easier for new developers to understand.

**Comment by blulady** [comment]
@Sebster3 & @mjshelton12 hey, when you guys get a chance please put down etas to re-review this pr?

**Comment by Sebster3** [comment]
ETA: 07/15

**Review by Sebster3 — APPROVED** [review]
Good work on the revisions for this PR @pdimaano. The formatting appears correct both locally and on GitHub, the site builds successfully, and the issue is addressed correctly. The extra time spent on formatting is noticed and appreciated, thank you!

File: assets/js/wins.js (hunk 2 above)
Comment (Sebster3) [reply assets/js/wins.js]: I'm marking as implicitly resolved following @roslynwythe's PR approval.
